# Site Settings
locale                   : "en-US"
title                    : "Carlos F. Gould"
title_separator          : "-"
name                     : &name "Carlos F. Gould"
description              : &description "Environmental health scientist studying the relationships between energy, air pollution, and health."
url                      : https://gouldc.github.io
baseurl                  : ""
repository               : "gouldc/gouldc.github.io"
site_theme               : "catalog"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false
atom_feed:
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : gould_cf
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
social:
  type                   :
  name                   :
  links:

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Carlos F. Gould"
  avatar           : "gould_headshot.jpg"
  bio              : "Assistant Professor, Public Health"
  email            : cagould@health.ucsd.edu
  employer         : 'UC San Diego'
  location         : "San Diego, CA"
  googlescholar    : "https://scholar.google.com/citations?hl=en&pli=1&user=MMDZBjgAAAAJ"
  github           : "gouldc"
  twitter          : "gould_cf"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections: {}

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_author_avatar: false
      read_time: true
      comments: true
      share: true
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      show_author_avatar: false
      sidebar: []

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# GitHub Metadata
github: null

# Redirects
redirect_from:
  json: false
  data_source: _data/redirects.yml
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
